export const NO_FILE = 'Keine Datei/Ordner ausgewählt';
export const NO_FILE_DETAILS = 'Bitte eine Datei order Ordner auswählen um Details anzuzeigen'
export const FOLDER_HEADER = 'Ordner';
export const FILE_HEADER = 'Dateien';
export const NEW_FOLDER = 'Neuer Ordner';
export const DOWNLOAD_TOOLTIP = 'Download';
export const DELETE_TOOLTIP = 'Löschen';
export const RENAME_TOOLTIP = 'Umbennen';
export const UPLOAD = 'Upload';
export const LOG_OUT = 'Abmelden';
export const SECOND_NAV_INITPATH = 'Start';
export const APPBAR_HEADER = 'File-Browser';
export const DETAILS_TYPE = 'Typ';
export const DETAILS_SIZE = 'Größe';
export const DETAILS_CHANGED = 'Zuletzt geändert'
export const DETAILS_MADE = 'Erstellt';
export const DETAILS_SAVE = 'Speicherort';
export const LOGIN_USERNAME = 'Benutzername';
export const LOGIN_PASSWORD = 'Passwort';
export const LOGIN_HEADER_BUTTON = 'Anmelden';
export const NEW_FOLDER_HEADER = 'Neuen Ordner anlegen';
export const NEW_FOLDER_INPUT_FIELD = 'Ordnername'